### ISSUE TITLE
arquillian-payara-server-remote not connecting to remote host

### ISSUE THREAD

**Issue by phillipross** [payara/ecosystem-arquillian-connectors#51]
I'm trying to get arquillian-payara-server-remote to deploy to and test against a payara server running in a separate docker container, but it always seems to try to connect to localhost despite the configuration.  I've tried working with patched-src-javaee8-samples repo which defines a remote server profile and it behaves the same way.  The payara docs look to be outdated for the remote connector too, so I'm not even sure if I'm using the correct configuration parameters or not.  The patched-src-javaee8-samples repo appears to use a configuration that i've not seen anywhere else:
```
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <javaEEServer>payara-remote</javaEEServer>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
```

Any thoughts how I can narrow down where the problem might be?

**Comment by jGauravGupta** [comment]
Hi @phillipross ,

Can you share the Arquillian test log and Is the Payara Server domain secured?

**Comment by phillipross** [comment]
In my initial testing the payara server domain was not secure, but I tried both ways and it seemed to make no difference.  I was thinking the best thing to do would be to take the patched-src-javaee8-samples repo and create a docker-compose which fires up 2 docker containers and tries to run the remote server tests against the payara container.  I'll turn that into a test case to reproduce and work through the issue.  thanks!

**Comment by phillipross** [comment]
Now that I'm digging into this further, I'm not even able to determine what properties I'm supposed to be using in the surefire plugin config to actually connect to a remote server.  I'm trying to use the newer connector:
```
<dependencies>
                <dependency>
                    <groupId>fish.payara.arquillian</groupId>
                    <artifactId>payara-client-ee8</artifactId>
                </dependency>

                <!-- The actual Arquillian connector -->
                <dependency>
                    <groupId>fish.payara.arquillian</groupId>
                    <artifactId>arquillian-payara-server-remote</artifactId>
                    <version>2.0</version>
                    <scope>test</scope>
                    <optional>true</optional>
                </dependency>
            </dependencies>
```

And I'm just guessing at the surefire properties at this point:
```
<plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <javaEEServer>payara-remote</javaEEServer>
                                <adminHttps>true</adminHttps>
                                <adminPort>4848</adminPort>
                                <adminUser>admin</adminUser>
                                <adminPassword>admin</adminPassword>
                                <target>${test.server.hostname}</target>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
```

**Comment by phillipross** [comment]
I think I made a little progress in figuring this out.  I realized the properties are apparently supposed to be placed in the arquillian.xml, not the pom.xml.  I'll attempt to rework things to configure the connection this way and see if that works.

**Comment by phillipross** [comment]
I was able to make it work by configuring properties in the arquillian.xml, not the maven surefire configuration.  The real issue is that the documentation is wrong/outdated:
https://github.com/payara/Payara-Server-Documentation/issues/709
