### ISSUE TITLE
Add Jakarta EE 9 Support

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-arquillian-connectors#95]
Upgrade the Arquillian core to 1.7.0, and add Jakarta EE 9 and Junit 5 support.

**Comment by lprimak** [comment]
Arquillian 1.7.0 has not been released yet, but alpha is available in nexus.payara.fish payara-artifacts repository,
with support for JUnit 5

**Comment by hantsy** [comment]
Thanks. Just explore the `2.3.1.1-arq-1.7.0.Alpha5` version, it seems it does not align with Jakarta EE9, https://nexus.payara.fish/repository/payara-artifacts/fish/payara/arquillian/arquillian-payara-server-remote/2.3.1.1-arq-1.7.0.Alpha5/arquillian-payara-server-remote-2.3.1.1-arq-1.7.0.Alpha5.pom

**Comment by lprimak** [comment]
As far as I can see, Arquillian ecosystem has no dependencies on Java or Jakarta EE, so there is no need to 'align'
Shrinkwrap does have some dependencies on javax.inject but that's out of Payara scope currently, and I don't think that's an issue anyway

**Comment by hantsy** [comment]
In the Arquillian, I saw a series of new artifacts for Jakarta EE9, which postfix is with **jakarta**.  For example, for Jakarta EE 9 applications, it used Jakarta Servlet 5.0 protocol.  And Open Liberty also followed these rules add new jakarta EE 9 support with a new artifactId, eg. **arquillian-liberty-managed-jakarta**.

Ok, I will try this version `2.3.1.1-arq-1.7.0.Alpha5` in [my sample project](https://github.com/hantsy/jakartaee9-starter-boilerplate). Thanks a lot.

**Comment by hantsy** [comment]
Check the result. https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/64/checks

When ran it on my local system, I saw the payara arquillian itself tried to resolve deps of Jakarta EE 8, and almost all failure is because lack of Jakarta EE 8 APIs.

**Comment by hantsy** [comment]
> so there is no need to 'align' to Jakarta EE 9

Do you still think it works with Jakarta EE 9?

**Comment by lprimak** [comment]
Feel free to open another issue that’s targeted at Jakarta ee 9. And please make it easy to follow, paste the relevant logs etc. 
currently this ticket is too close to something like “this isn’t working in my project “ and is too broad and not easily actionable

**Comment by hantsy** [comment]
>currently this ticket is too close to something like “this isn’t working in my project “ and is too broad and not easily actionable

I added the dev version to my sample is to reproduce the issues.  What is the meaning of **this isn’t working in my project**?

>As far as I can see, Arquillian ecosystem has no dependencies on Java or Jakarta EE, so there is no need to 'align'

As far as I know, all adapters are dependent on Java EE/Jakarta EE API, including Payara arquillian adapters.

**Comment by lprimak** [comment]
I think I see what you are getting at, and I see why I am so confused :)
Although Payara can run Jakarta EE 9 applications currently, full Jakarta EE 9 implementation will only come with Payara 6, and thus arquillian connectors will have to wait for that.
For now, you need to have both APIs (8 & 9) to run Arquillian tests against Payara.
There is a plan in place for Payara 6 as well as (obviously) arquillian connectors for that.

**Comment by lprimak** [comment]
I will let Payara support answer any other questions, because I think I've stepped on their toes way too much already.
